# -*- mode: conf -*-

title: Crystal Sight
email: carl.xiong AT yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  See further, but how far is far?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://carltonf.github.io"
author: "@carltonf"
author_name: "Carl Xiong"
twitter_username: 
github_username: carltonf
site_repo: https://github.com/carltonf/carltonf.github.io

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
highlighter: rouge
exclude: [Makefile, tools, Gemfile, Gemfile.lock]

encoding: utf-8
# NOTE default collections get some special treating, and thus the 'index.html'
# for it must be a separate page that has *different* path, '/posts' for now.
permalink: /post/:title

collections:
  wiki:
    output: true
    permalink: /wiki/:title.html

paginate: 7
paginate_path: "/posts/page:num/"
## to have plugins run, disable this setting
# safe: true
gems:
  - jekyll-sitemap
  - jekyll-paginate
