# -*- mode: conf -*-
# Site settings
title: Crystal Sight
email: carl.xiong AT yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  See further, but how far is far?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://carltonf.github.io" # the base hostname & protocol for your site
author: "@carltonf"
author_name: "Carl Xiong"
twitter_username: 
github_username: carltonf

highlighter: rouge
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

encoding: utf-8
permalink: /:title

collections:
    wiki:
      output: true
      permalink: /wiki/:title.html

## to have plugins run, disable this setting
# safe: true
gems:
  - jekyll-sitemap