#!/bin/bash

function usage {
    cat - <<END
Usage: habit <command> [post]
Available commands: new-draft publish unpublish diff commit serve
NOTE: Relying on docker 'carltonf/jekyll-toolbox'.
END
}

function commit {
    local working_post="$1"

    # NOTE fish doesn't have heredoc, which is inconvenient in such case
    git log --format=%B -n 1 -- $working_post \
        | sed -e '/^[^#]/ s/^/# /g' \
        | cat - $TOP/tools/habit/git-template \
        | git commit -F - -e -- $working_post
}

function serve {
    local PORT=4000
    local limit_posts=2
    # TODO what `--label` use here.
    # NOTE Use `--force_polling`, so it works with vboxsf
    DOCKER_RUN_OPTS="--name=carltonf-blog --label=jekyll -p ${PORT}:4000" \
                   jekyll serve --drafts --watch --incremental \
                   --limit_posts $limit_posts --force_polling
}


cmd="$1"
post="$2"
title="$2"
if [ x"$post" = x ]; then
    # echo "* WARNING: working post is not set, choose the first modified post."
    post=$(git status -s _posts/ _drafts/ | awk '/M/ {print $2; exit}')
    title=""
fi

# TODO fish auto-completion
case "$cmd" in
    new-draft)
        jekyll draft "$title"
        ;;
    publish)
        jekyll publish "$post"
        ;;
    unpublish)
        jekyll unpublish "$post"
        ;;
    diff)
        git diff HEAD -- "$post"
        ;;
    commit)
        commit "$post"
        ;;
    serve)
        serve
        ;;
    *)
        echo "* Error: unknown command '$cmd'."
        usage
        ;;
esac
